version: "3.7"

services:
  region:
    container_name: region-metric
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - .:/app
    command: "npm run start"
  mongo:
    image: mongo:4.4.5
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
  metabase:
    image: metabase/metabase:v0.39.1
    ports:
      - 3000:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase:/metabase-data
    depends_on:
      - mongo
  ingester:
    build: .
    depends_on:
      - mongo
volumes:
  region:
  mongodb:
  metabase:
